import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Link from "next/link";
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <div className="flex items-center justify-center w-full h-screen bg-white text-black ">
            <div className="bg-white shadow-lg rounded-xl p-16 flex flex-col items-center w-full max-w-2xl">
                <Link href={'/'} className="underline text-2xl">Todo List</Link>{children}
            </div>
        </div>

        </body>
        </html>
    );
}
